CREATE TRIGGER CUSTOMER_INSERT ON CUSTOMER AFTER
INSERT AS BEGIN
UPDATE
    CUSTOMER set creaon_date = {ts '3099-01-01 00:00:00'} FROM CUSTOMER c inner join inserted i on c.id=i.id
END

GO
CREATE TRIGGER CUSTOMER_UPDATE ON CUSTOMER AFTER
UPDATE AS BEGIN
UPDATE
    CUSTOMER set creaon_date = {ts '3099-01-01 00:00:00'} FROM CUSTOMER c inner join inserted i on c.id=i.id
END